Repository BorisMarin8004/FlightTicket, pull requests merged in 2021-09, with the labels that each got.

#6 Retrofit and api
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/flightticket/API/API.java
  app/src/main/java/com/example/flightticket/API/APIResponseClasses/APICarrier.java
  app/src/main/java/com/example/flightticket/API/APIResponseClasses/APICurrency.java
  app/src/main/java/com/example/flightticket/API/APIResponseClasses/APIOutboundLeg.java
  app/src/main/java/com/example/flightticket/API/APIResponseClasses/APIPlace.java
  app/src/main/java/com/example/flightticket/API/APIResponseClasses/APIQuote.java
  app/src/main/java/com/example/flightticket/API/APIResponseClasses/APIResponse.java
  app/src/main/java/com/example/flightticket/API/APIResponseClasses/APIResponseConverters/APIResponseToDataClassConverters.java
  app/src/main/java/com/example/flightticket/API/APIResponseClasses/APIResponseConverters/ConvertersFunctionInterface.java
  app/src/main/java/com/example/flightticket/API/HeaderInterceptor.java
  app/src/main/java/com/example/flightticket/API/LoggingInterceptor.java
  app/src/main/java/com/example/flightticket/API/RetrofitClient.java
  app/src/main/java/com/example/flightticket/DataClasses/Flight.java
  app/src/main/java/com/example/flightticket/DataClasses/Place.java
  app/src/main/java/com/example/flightticket/MainActivity.java
  app/src/test/java/com/example/flightticket/APITests/APITests.java
  app/src/test/java/com/example/flightticket/ExampleUnitTest.java
  app/src/test/java/com/example/flightticket/OtherTests.java
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#7 Create account
  app/build.gradle
  app/src/androidTest/java/com/example/flightticket/DBTest/UserDBTest.java
  app/src/androidTest/java/com/example/flightticket/ExampleInstrumentedTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/flightticket/CreateActivity.java
  app/src/main/java/com/example/flightticket/DataClasses/User.java
  app/src/main/java/com/example/flightticket/TypeConverters/ListTypeConverter.java
  app/src/main/java/com/example/flightticket/db/UserDAO.java
  app/src/main/java/com/example/flightticket/db/UserDatabase.java
  app/src/main/res/layout/activity_create.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/example/flightticket/CreateAccountTest.java
Labels: enhancement

#20 Update readme
  FlightTicketFigma.png
  README.md
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: documentation

#23 Update README.md
  README.md
Labels: bug

#24 Logout & SharedPreferences
  app/build.gradle
  app/src/main/java/com/example/flightticket/CreateActivity.java
  app/src/main/java/com/example/flightticket/HomeActivity.java
  app/src/main/java/com/example/flightticket/LandingActivity.java
  app/src/main/java/com/example/flightticket/LoginActivity.java
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/example/flightticket/CreateAccountTest.java
Labels: enhancement

#25 Flights filter and adapter
  app/build.gradle
  app/src/androidTest/java/com/example/flightticket/DBTest/UserDBTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/flightticket/CreateActivity.java
  app/src/main/java/com/example/flightticket/DB/UserDAO.java
  app/src/main/java/com/example/flightticket/DB/UserDatabase.java
  app/src/main/java/com/example/flightticket/DataClasses/User.java
  app/src/main/java/com/example/flightticket/HomeActivity.java
  app/src/main/java/com/example/flightticket/LandingActivity.java
  app/src/main/java/com/example/flightticket/LoginActivity.java
  app/src/main/java/com/example/flightticket/MainActivity.java
  app/src/main/java/com/example/flightticket/SearchFlights.java
  app/src/main/java/com/example/flightticket/utils/FlightDataGetter.java
  app/src/main/java/com/example/flightticket/utils/FlightsAdapter.java
  app/src/main/res/drawable/dialog_flight_info_background.xml
  app/src/main/res/drawable/gradient_background.xml
  app/src/main/res/drawable/list_item_flight_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_search_flights.xml
  app/src/main/res/layout/dialog_flight_info.xml
  app/src/main/res/layout/list_item_flight.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/test/java/com/example/flightticket/APITests/APITests.java
  app/src/test/java/com/example/flightticket/LoginTest.java
  app/src/test/java/com/example/flightticket/OtherTests.java
  build.gradle
Labels: enhancement

#30 Filter and request dialog
  app/src/androidTest/java/com/example/flightticket/DBTest/UserDBTest.java
  app/src/androidTest/java/com/example/flightticket/ExampleInstrumentedTest.java
  app/src/androidTest/java/com/example/flightticket/FilterTests.java
  app/src/main/java/com/example/flightticket/DataClasses/User.java
  app/src/main/java/com/example/flightticket/SearchFlights.java
  app/src/main/java/com/example/flightticket/utils/FlightDataGetter.java
  app/src/main/java/com/example/flightticket/utils/FlightDialog.java
  app/src/main/java/com/example/flightticket/utils/FlightFilterDialog.java
  app/src/main/java/com/example/flightticket/utils/FlightInfoDialog.java
  app/src/main/java/com/example/flightticket/utils/FlightRequestDialog.java
  app/src/main/java/com/example/flightticket/utils/FlightsAdapter.java
  app/src/main/res/layout/activity_search_flights.xml
  app/src/main/res/layout/dialog_flight_filter.xml
  app/src/main/res/layout/dialog_flight_info.xml
  app/src/main/res/layout/dialog_flight_request.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
